---
# This playbook contains common plays that will be run on all nodes.

- name: Autoremove unused packages
  become: true
  command: apt -y autoremove
  register: autoremove_output
#  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
  changed_when: "'0 upgraded' not in autoremove_output.stdout"
  tags:
    - apt
    - autoremove

- name: Update cache
  become: true
  apt:
    update_cache: yes
  tags:
    - apt
    - updatecache

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist
  tags:
    - apt
    - upgrade

#  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
